extensions = {
    "normal": ["jpg", "jpeg", "png", "gif", "pdf", "mp3", "mp4", "txt", "csv", "svg"],

    "php": ["php", "php3", "phar", "phtml", "php5", "php6", "php7", "phps", 
    "pht", "phtm","php4", "pgif", "php2", "inc", "hphp", "ctp", "module"]
}
null_bytes = [
    '\x00',
    "%20",
    "%0a",
    "%00",
    "%0d%0a",
    "/",
    ".\\",
    ".",
    "...."
]
mimetypes = {
    "com": "application/octet-stream",
    "php": "application/x-httpd-php",
    "php2": "application/x-httpd-php",
    "php3": "application/x-httpd-php",
    "php4": "application/x-httpd-php",
    "php5": "application/x-httpd-php",
    "php6": "application/x-httpd-php",
    "php7": "application/x-httpd-php",
    "phps": "application/x-httpd-php",
    "pht": "application/x-httpd-php",
    "phtm": "application/x-httpd-php",
    "phtml": "application/x-httpd-php",
    "pgif": "application/x-httpd-php",
    "htaccess": "application/x-httpd-php",
    "phar": "application/x-httpd-php",
    "inc": "application/x-httpd-php",
    "hphp": "application/x-httpd-php",
    "ctp": "application/x-httpd-php",
    "module": "application/x-httpd-php",
    "txt": "text/plain",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "gif": "image/gif",
    "pdf": "application/pdf", 
    "mp3": "audio/mpeg", 
    "mp4": "video/mp4",
    "txt": "text/plain",
    "csv": "text/csv",
    "svg": "image/svg+xml",
}
magic_bytes = {
    "jpg": b'\xFF\xD8\xFF\xE0',
    "jpeg": b'\xFF\xD8\xFF\xE0',
    "png": b'\x89\x50\x4E\x47\x0D\x0A\x1A\x0A',
    "gif": b'GIF89',
    "bmp": b'BM',
    "zip": b'PK',
    "rar": b'Rar!',
    "exe": b'MZ',
    "pdf": b'%PDF',
    "docx": b'PK',
    "xlsx": b'PK',
    "pptx": b'PK',
    "mp3": b'ID3',
    "wav": b'RIFF',
    "mp4": b'ftypisom',
    "avi": b'RIFF',
    "mkv": b'\x1A\x45\xDF\xA3',
    "txt": b'\xEF\xBB\xBF',
    "html": b'<!DOCTYPE html>',
    "js": b'// JavaScript',
    "tar": b'ustar',
    "iso": b'CD001',
    "dll": b'MZ',
    "xml": b'<?xml',
    "json": b'{\n  \"',
    "asp": b'<%\n',
    "class": b'\xCA\xFE\xBA\xBE',
    "doc": b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1',
    "ppt": b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1',
    "xls": b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1',
    "ttf": b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1',
    "otf": b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1',
    "woff": b'wOFF',
    "woff2": b'wOF2',
    "ttc": b'ttcf',
    "mov": b'moov',
    "flv": b'FLV',
    "ogg": b'OggS',
    "aac": b'\xFF\xE1',
    "flac": b'fLaC',
    "psd": b'8BPS',
    "svg": b'<svg',
    "ai": b'\xC5d',
    "eps": b'%!PS',
    "tif": b'II*\x00',
    "tiff": b'II*\x00',
    "ico": b'\x00\x00\x01\x00',
    "dmg": b'koly',
    "apk": b'PK',
    "deb": b'21',
    "rpm": b'\xED\xAB\xEE',
    "mpg": b'\x00\x00\x01\xBA',
    "mpeg": b'\x00\x00\x01\xBA',
    "webm": b'\x1A\x45\xDF\xA3',
    "gz": b'\x1F\x8B',
    "xz": b'\xFD7zXZ\x00',
    "jar": b'PK\x03\x04',
    "bz2": b'BZh',
    "csv": b'ID,Timestamp',
    "sql": b'CREATE TABLE',
    "bak": b'BACKUP',
    "cfg": b'CONFIG',
    "ini": b'[',
    "bat": b'@echo off',
    "sh": b'#!/bin/bash',
    "pl": b'#!/usr/bin/perl',
    "rb": b'#!/usr/bin/env ruby',
    "h": b'#include',
    "cpp": b'#include <iostream>',
    "py": b'#!/usr/bin/env python',
    "java": b'public class',
    "php": b'<?php',
    "css": b'/* CSS */',
}

# Operational stuff
progress_bar = {
    "current": 0,
    "max": 0
}
protocol = "https"